### ISSUE TITLE
Using blank queue name results in error on reconnection

### ISSUE THREAD

**Issue by leearmstrong** [assembla/cony#18]
When using an auto named queue it seems that it creates it fine first time but on a reconnect the RabbitMQ server issues the following error.

```
Client error: Exception (403) Reason: "ACCESS_REFUSED - queue name 'amq.gen-zOW_J2f1kRwrKFY-DvZBGw' contains reserved prefix 'amq.*'"
Client error: Exception (504) Reason: "channel/connection is not open"
Client error: Exception (504) Reason: "channel/connection is not open"
Consumer error: Exception (404) Reason: "NOT_FOUND - no previously declared queue"
```

Then no messages are received and it won't work again until a restart.  I presume it is trying to use the name it connected with on the first connection and try to recreate that queue but due to the name it is not allowed.

**Comment by kron4eg** [comment]
@leearmstrong hey, thanks for report. It's fixed now, please update.

**Comment by leearmstrong** [comment]
No problem at all.  I've just started with Go and cony is awesome!
