### ISSUE TITLE
 value method github.com/streadway/amqp.Error.Error called using nil *Error pointer

### ISSUE THREAD

**Issue by JeffreyBool** [assembla/cony#33]
panic: value method github.com/streadway/amqp.Error.Error called using nil *Error pointer

goroutine 1 [running]:
github.com/streadway/amqp.(*Error).Error(0x0, 0xc0000a3d40, 0x0)
	<autogenerated>:1 +0x117
github.com/getsentry/sentry-go.(*Client).eventFromException(0xc0001b5180, 0xd0da00, 0x0, 0xc06b30, 0x5, 0xc000272c00)
	/root/go/pkg/mod/github.com/getsentry/sentry-go@v0.3.0/client.go:304 +0x164
github.com/getsentry/sentry-go.(*Client).CaptureException(0xc0001b5180, 0xd0da00, 0x0, 0xc000272c00, 0xd0d220, 0xc0001b4c80, 0xc0000fb738)
	/root/go/pkg/mod/github.com/getsentry/sentry-go@v0.3.0/client.go:199 +0x58
github.com/getsentry/sentry-go.(*Hub).CaptureException(0xc0001ba4e0, 0xd0da00, 0x0, 0x3)
	/root/go/pkg/mod/github.com/getsentry/sentry-go@v0.3.0/hub.go:235 +0xe4
main.captureException(0xd0da00, 0x0)
	/root/go/src/apush/serve.go:169 +0x13d
main.main()
	/root/go/src/apush/serve.go:150 +0xe55

**Comment by peczenyj** [comment]
you should post this issue to project github.com/streadway/amqp
