### ISSUE TITLE
Client won't reconnect after second amqp.Dial timeout 

### ISSUE THREAD

**Issue by gustav-b** [assembla/cony#4]
**Steps to reproduce**:

1. Start a RabbitMQ server.

2. Start an instance of the [basic example consumer](https://github.com/assembla/cony/tree/master/examples/basic/consumer) that connects to the server.

3. Stop the RabbitMQ server so that doesn't close the connection, but won't respond. For example send `SIGSTOP` to the process or issue `docker pause` if the server is running in a docker container.<br />
After about 30 seconds will output a timeout error:<br/>
   ```
   Client error: Exception (501) Reason: "read tcp 33.33.33.1:61434->33.33.33.60:5672: i/o timeout"
   ```
Wait some more to get a second error.
4. Resume the RabbitMQ, e.g. by sending `SIGCONT` to the process or issuing `docker unpause`.

5. Try sending a message to the consumer using the [basic example prodcuer](https://github.com/assembla/cony/tree/master/examples/basic/producer).

**Expected result**:
The consumer should reconnect and receive the message.

**Actual result**:
The consumer doesn't reconnect and will not receive the message.

It looks like [`(*Client).Loop`](https://github.com/assembla/cony/blob/0843c27d68b699abe13f494e32a27c3e6abfe5d4/client.go#L114) stores the connection even if `amq.Dial` fails and that the broken connection is used on further iterations. The fix should be to not store the connection until after the error has been checked.

**Comment by kron4eg** [comment]
@gustav-b can you please show stack traces in the event when program stuck? Sending SIGABRT/SIGQUIT to consumer should generate one.

**Comment by kron4eg** [comment]
If `amqp.Dial()` fails by any reason (timeout included), `conn` will be `(*amqp.Connection)(nil)`, and this will be stored in `c.conn`, so I don't think it's the reason.

**Comment by gustav-b** [comment]
Sure, here is a trace of the consumer after it has entered the stucked state:
```
Consumer is running

Flags:
  -url string
          amqp url (default "amqp://guest:guest@localhost/")


Client error: Exception (501) Reason: "read tcp 33.33.33.1:51694->33.33.33.60:5672: i/o timeout"
Client error: Exception (501) Reason: "read tcp 33.33.33.1:51882->33.33.33.60:5672: i/o timeout"
^\SIGQUIT: quit
PC=0x5c5db m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0xd03, 0x2, 0xc8200be0b0, 0x200000008, 0xc820030701, 0x435300, 0x4f479, 0xffffffffffffffff, 0x435300, 0x7fff5fbff05c, ...)
/opt/local/lib/go/src/runtime/sys_darwin_amd64.s:407 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x435300)
/opt/local/lib/go/src/runtime/os1_darwin.go:395 +0xe5
runtime.semasleep.func1()
/opt/local/lib/go/src/runtime/os1_darwin.go:411 +0x29
runtime.systemstack(0x7fff5fbff060)
/opt/local/lib/go/src/runtime/asm_amd64.s:278 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
/opt/local/lib/go/src/runtime/os1_darwin.go:412 +0x36
runtime.notesleep(0x435750)
/opt/local/lib/go/src/runtime/lock_sema.go:169 +0x100
runtime.stopm()
/opt/local/lib/go/src/runtime/proc1.go:1136 +0x112
runtime.findrunnable(0xc82001f500, 0x0)
/opt/local/lib/go/src/runtime/proc1.go:1538 +0x69e
runtime.schedule()
/opt/local/lib/go/src/runtime/proc1.go:1647 +0x267
runtime.goexit0(0xc820001b00)
/opt/local/lib/go/src/runtime/proc1.go:1773 +0x1a2
runtime.mcall(0x7fff5fbff1e0)
/opt/local/lib/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [select]:
main.main()
/Users/gustav/src/go/src/github.com/assembla/cony/examples/basic/consumer/consumer.go:60 +0x8ad

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
/opt/local/lib/go/src/runtime/asm_amd64.s:1721 +0x1

rax    0xe
rbx    0xd03
rcx    0x7fff5fbfefe8
rdx    0x7fff5fbff060
rdi    0xd03
rsi    0x435300
rbp    0x435640
rsp    0x7fff5fbfefe8
r8     0x435640
r9     0x600710
r10    0x10
r11    0x286
r12    0x2
r13    0x34bdad
r14    0x2
r15    0x8
rip    0x5c5db
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by kron4eg** [comment]
@gustav-b I was able to reproduce this only by running custom made listener on AMQP port, which did't replied anything back to connected client and didn't event read what was sent :) Didn't saw such behaviour from rabbitmq in production. But anyway, I've fixed this. Soon someone from assembla will merge this.

**Comment by gustav-b** [comment]
@kron4eg, Great, thank you!
