### ISSUE TITLE
Reconnection error Exception (501) Reason: "EOF"

### ISSUE THREAD

**Issue by sebastienfr** [assembla/cony#7]
Hello,

Hello, running on docker with a bridged network, in the client reconnection loop, when running the amqp.Dial, it returns a connection but also an error. This causes the user client to start listening on the deliveries on a faulty connection.

Here are some logs I added in the client.Loop for debugging, giving the content of the connection and errors.

I'm preparing a PR to set the connection to `nil` in case an error is returned when dialing to fix the issue.

`
Dialing new connection
Storing new connection &{{{%!V(int32=+0) %!V(uint32=+0)} %!V(uint32=+1)} {%!V(int32=+0) %!V(uint32=+0)} {%!V(int32=+0) %!V(uint32=+0)} %!V(*net.TCPConn=&{{+0xc8201d6540}}) %!V(chan amqp.message=+0xc8201c8d20) %!V(*amqp.writer=&{+0xc8201afb80}) %!V(chan time.Time=+0xc8201c8d80) %!V(chan amqp.readDeadliner=+0xc8201c8e40) %!V(*amqp.allocator=<nil>) map[] %!V(bool=true) [] [] %!V(chan *amqp.Error=+0xc8201c8de0) {[] %!V(string=) %!V(int=+0) %!V(int=+0) %!V(time.Duration=+0) %!V(*tls.Config=<nil>) map[] %!V(func(string, string) (net.Conn, error)=<nil>)} %!V(int=+0) %!V(int=+0) map[]}

Reporting error dialing &{%!V(int=+501) %!V(string=EOF) %!V(bool=false) %!V(bool=false)}

Entering connection loop

Loading connection

Connection not nil

time="2016-02-22T16:05:23Z" level=warning msg="client error" error="Exception (501) Reason: \"EOF\""
`

**Comment by sebastienfr** [comment]
Looks like my issue is the same as #4. My version of cony was not up to date with your latest fix.

**Comment by kron4eg** [comment]
heh, nice :)
